### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by Brideau** [rob-murray/slowwly#5]
Hi there,

I'm running a local version of this and am making request to it from a browser, but I get the error "No 'Access-Control-Allow-Origin' header is present on the requested resource."

I'm not a Ruby developer, unfortunately, so I'm not sure how to modify the source to allow Sinatra to serve responses with the correct header to allow this.

Any advice?

**Comment by rob-murray** [comment]
Hi,
Are you using this from JS then? Yes, I guess that would cause this error.

I have only used this for testing "backend" API calls so never run into this problem, I can change the Sinatra app to add CORS headers... give me a couple of days to get around to it.

Thanks.

**Comment by Brideau** [comment]
Hi Rob, thanks for the quick response! Yes I'm making the calls from client-side javascript. 

I appreciate the help!
